### ISSUE TITLE
2.[JitsiMeetJs.js]"<n>" "Analytics disabled,disposing

### ISSUE THREAD

**Issue by wkingredxx123** [roy2651/react-native-lib-jitsi-meet#1]
Hello, I just learned to use the reactnative framework, I clicked on the "start meeting" button in the project, and then he made the following mistake:
I'm using a Samsung 'SM-G9350' phone.
1.[modules/statistics/AnalyticsAdapter.js]"<n>:" "Disposing of analytics adapter"
2.[JitsiMeetJs.js]"<n>" "Analytics disabled,disposing"
 what caused this error, how to solve this problem, can you guide the following? Thank you.

**Comment by roy2651** [comment]
my app also show this.
and this is warning 
we can together figure it out

**Comment by wkingredxx123** [comment]
Ok, I'm also thinking about how to solve this problem.

**Comment by roy2651** [comment]
@wkingredxx123 when i run-android with realse and no warning
but I don‘t know this can effect something

**Comment by roy2651** [comment]
@wkingredxx123 modefy 
const initOptions = {
  disableAudioLevels: true,
  enableAnalyticsLogging: true
};
this waring can be fixed
